theme: TintedGlass
disableNewStartMenuLayout: ""
styleConstants:
  - ""
controlStyles:
  - target: ""
    styles:
      - ""
themeResourceVariables:
  - ""
webContentStyles:
  - target: ""
    styles:
      - ""
webContentCustomJs: ""
