iconTheme: Sweet Rainbow|themes/icons/niivu/Sweet-Rainbow.zip
disableThumbnails: 1
allResourceRedirect: 0
themePaths:
  - ""
redirectionResourcePaths:
  - original: ""
    redirect: ""
themeFolder: ""
